#!/usr/bin/env node
/* Writes sw.js: the service worker that keeps the whole site on the device for offline use.
 * Run after changing any file the children use (the audio and data scripts run it for you):
 *     node tools/build_sw.js           write sw.js
 *     node tools/build_sw.js --check   exit 1 if sw.js is out of date (used by tools/check_data.js)
 * The version is a hash of all the files, so any change makes devices download the new files. */
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const ROOT = path.resolve(__dirname, "..");
const PAGES = ["index.html", "letter.html", "exercise.html", "review.html", "teacher.html", "content.html"];
const DIRS = ["css", "js", "data", "img", "audio", "fonts"];
const SKIP = /\.(md|txt|py|map)$|(^|\/)\./;

function walk(dir) {
  return fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).flatMap((d) => {
    const rel = dir + "/" + d.name;
    if (SKIP.test(rel)) return [];
    return d.isDirectory() ? walk(rel) : [rel];
  });
}
const files = PAGES.concat(...DIRS.map(walk)).sort();
const hash = crypto.createHash("sha1");
files.forEach((f) => { hash.update(f); hash.update(fs.readFileSync(path.join(ROOT, f))); });
const version = hash.digest("hex").slice(0, 12);

const sw = `/* Offline support for Huroofi. GENERATED by tools/build_sw.js – do not edit by hand.
 * After the first visit every page, picture, sound and font is kept on the device, so the site works
 * without internet (YouTube videos excepted). Pages, scripts and content (data/letters.js) are fetched
 * fresh when online, so edits appear at once; pictures, sounds and fonts come from the device and are
 * refreshed quietly in the background. Only this site's own files are handled; YouTube is untouched. */
const VERSION = ${JSON.stringify(version)};
const CACHE = "huroofi-" + VERSION;
const FILES = ${JSON.stringify(["./"].concat(files))};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE)
    .then((c) => c.addAll(FILES.map((f) => new Request(f, { cache: "reload" }))))
    .then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith("huroofi-") && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// The teacher page asks how much is saved for offline use.
self.addEventListener("message", (e) => {
  if (e.data !== "status" || !e.source) return;
  caches.open(CACHE).then((c) => c.keys()).then((keys) => e.source.postMessage({ version: VERSION, total: FILES.length, saved: keys.length }));
});

self.addEventListener("fetch", (e) => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== "GET" || url.origin !== self.location.origin) return;
  if (req.mode === "navigate" || /\\.(html|js|css)$/.test(url.pathname)) e.respondWith(networkFirst(req));
  else e.respondWith(fromCache(req));
});

function timeout(ms) { return new Promise((_, rej) => setTimeout(() => rej(new Error("timeout")), ms)); }

async function networkFirst(req) {
  const cache = await caches.open(CACHE);
  try {
    const res = await Promise.race([fetch(req), timeout(4000)]);
    if (res.ok) cache.put(stripSearch(req), res.clone());
    return res;
  } catch (err) {
    return (await cache.match(req, { ignoreSearch: true })) || (await cache.match("index.html")) || Response.error();
  }
}

// Pictures, sounds, fonts: answer from the device at once; refresh from the network in the background.
async function fromCache(req) {
  const cache = await caches.open(CACHE);
  const key = new Request(req.url);            // never cache partial (range) responses
  let res = await cache.match(key, { ignoreSearch: true });
  const refresh = fetch(key).then((r) => { if (r.ok && r.status === 200) cache.put(key, r.clone()); return r; }).catch(() => null);
  if (!res) res = await refresh;
  if (!res) return Response.error();
  const range = req.headers.get("range");
  return range ? partial(res, range) : res;
}

// Safari asks for sounds in pieces (Range requests) and needs a 206 answer.
async function partial(res, range) {
  const buf = await res.clone().arrayBuffer();
  const m = /bytes=(\\d*)-(\\d*)/.exec(range) || [];
  const size = buf.byteLength;
  let start = m[1] ? parseInt(m[1], 10) : 0, end = m[2] ? parseInt(m[2], 10) : size - 1;
  if (!m[1] && m[2]) { start = Math.max(0, size - parseInt(m[2], 10)); end = size - 1; }
  end = Math.min(end, size - 1);
  if (start > end) return new Response(null, { status: 416, headers: { "Content-Range": "bytes */" + size } });
  return new Response(buf.slice(start, end + 1), { status: 206, headers: {
    "Content-Type": res.headers.get("Content-Type") || "application/octet-stream",
    "Content-Range": "bytes " + start + "-" + end + "/" + size,
    "Content-Length": String(end - start + 1), "Accept-Ranges": "bytes" } });
}

function stripSearch(req) { const u = new URL(req.url); u.search = ""; return new Request(u.href); }
`;

const out = path.join(ROOT, "sw.js");
const old = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
if (process.argv.includes("--check")) {
  if (old !== sw) { console.log("sw.js is out of date: run  node tools/build_sw.js"); process.exit(1); }
  console.log(`sw.js up to date (${files.length} files, version ${version})`);
} else {
  fs.writeFileSync(out, sw);
  console.log(`sw.js: ${files.length} files, version ${version}`);
}
