#!/usr/bin/env node
/* Writes sw.js: the service worker that keeps the whole site on the device for offline use.
 * Run after changing any file the children use (the audio and data scripts run it for you):
 *     node tools/build_sw.js           write sw.js
 *     node tools/build_sw.js --check   exit 1 if sw.js is out of date (used by tools/check_data.js)
 * The version is a hash of all the files, so any change makes devices download the new files. */
const fs = require("fs"), path = require("path"), crypto = require("crypto");
const ROOT = path.resolve(__dirname, "..");
const PAGES = ["index.html", "letter.html", "exercise.html", "review.html", "teacher.html", "content.html"];
const DIRS = ["css", "js", "data", "img", "audio", "fonts"];
const SKIP = /\.(md|txt|py|map)$|(^|\/)\./;

function walk(dir) {
  return fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).flatMap((d) => {
    const rel = dir + "/" + d.name;
    if (SKIP.test(rel)) return [];
    return d.isDirectory() ? walk(rel) : [rel];
  });
}
const files = PAGES.concat(...DIRS.map(walk)).sort();
const sha = (buf) => crypto.createHash("sha1").update(buf).digest("hex").slice(0, 10);
const entries = files.map((f) => [f, sha(fs.readFileSync(path.join(ROOT, f)))]);
entries.unshift(["./", entries.find((e) => e[0] === "index.html")[1]]);
const version = sha(JSON.stringify(entries)).slice(0, 12);

const sw = `/* Offline support for Huroofi. GENERATED by tools/build_sw.js – do not edit by hand.
 * After the first visit every page, picture, sound and font is kept on the device, so the site works
 * without internet (YouTube videos excepted).
 * - Sounds are saved under an address that includes a hash of their content (audio/x.mp3?v=…; the hash
 *   comes from data/audio-manifest.js). A re-recorded sound has a new address, so an old saved copy can
 *   never be played instead of the new recording.
 * - Updates take over within seconds: only pages, scripts and interface pictures must be saved first;
 *   sounds and word pictures are saved in the background (and fetched directly when needed).
 * - Robust on poor Wi-Fi: every download is retried, and anything missing is filled in on later visits.
 * Only this site's own files are handled; YouTube is untouched. */
const VERSION = ${JSON.stringify(version)};
const CACHE = "huroofi-" + VERSION;
const META = "huroofi-meta";
const FILES = ${JSON.stringify(entries)};
const CORE = /(^\\.\\/$)|\\.(html|css|js|woff2)$|^img\\/ui\\//;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const url = (f) => new URL(f, self.registration.scope).href;
// The address a file is saved under: sounds carry their content hash, like the pages ask for them.
const key = (f, h) => url(/^audio\\//.test(f) ? f + "?v=" + h : f);

async function fetchWithRetry(u, tries = 4) {
  for (let i = 0; i < tries; i++) {
    const ctl = new AbortController(), timer = setTimeout(() => ctl.abort(), 20000);   // a stalled download never blocks
    try {
      const r = await fetch(new Request(u, { cache: "reload", signal: ctl.signal }));
      if (r.ok) { const body = await r.blob(); clearTimeout(timer); return new Response(body, { headers: r.headers }); }
      await r.arrayBuffer().catch(() => {});   // read and discard a failed answer, or its connection stays busy
    } catch (e) {}
    clearTimeout(timer);
    await sleep(400 * (i + 1));
  }
  throw new Error("could not download " + u);
}

async function pool(items, n, fn) {
  let i = 0;
  await Promise.all(Array.from({ length: n }, async () => { while (i < items.length) await fn(items[i++]); }));
}

// Download the files that are not saved yet. core=true: pages/scripts; false: sounds/pictures; undefined: all.
async function fill(core) {
  const cache = await caches.open(CACHE);
  const have = new Set((await cache.keys()).map((r) => r.url));
  const todo = FILES.filter(([f, h]) => !have.has(key(f, h)) && (core === undefined || CORE.test(f) === core));
  let failed = 0;
  await pool(todo, 6, async ([f, h]) => {
    try { await cache.put(key(f, h), await fetchWithRetry(key(f, h))); } catch (e) { failed++; }
  });
  return failed;
}

async function readMeta() {
  const r = await (await caches.open(META)).match("meta");
  return r ? r.json() : null;
}

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const meta = await readMeta();
    if (meta && meta.version !== VERSION) {   // copy files that did not change from the previous version
      const old = await caches.open("huroofi-" + meta.version);
      await pool(FILES, 8, async ([f, h]) => {
        if (meta.hashes && meta.hashes[f] === h) {
          const r = await old.match(url(f), { ignoreSearch: true });
          if (r) await cache.put(key(f, h), r);
        }
      });
    }
    if (await fill(true)) throw new Error("pages missing, will retry on the next visit");
    await self.skipWaiting();   // take over now; sounds and pictures are saved in the background
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith("huroofi-") && k !== CACHE && k !== META).map((k) => caches.delete(k)));
    await (await caches.open(META)).put("meta", new Response(JSON.stringify({ version: VERSION, hashes: Object.fromEntries(FILES) })));
    await self.clients.claim();
  })());
  fill();   // background: save the remaining sounds and pictures for offline use
});

let filling = null;
self.addEventListener("message", (e) => {
  if (e.data === "fill") {          // sent by every page: fill in anything not saved yet
    if (!filling) filling = fill().finally(() => { filling = null; });
    e.waitUntil(filling);
  } else if (e.data === "status" && e.source) {
    caches.open(CACHE).then((c) => c.keys()).then((keys) => e.source.postMessage({ version: VERSION, total: FILES.length, saved: keys.length }));
  }
});

self.addEventListener("fetch", (e) => {
  const req = e.request, u = new URL(req.url);
  if (req.method !== "GET" || u.origin !== self.location.origin) return;
  if (req.mode === "navigate" || /\\.(html|js|css)$/.test(u.pathname)) e.respondWith(networkFirst(req));
  else if (u.searchParams.has("v")) e.respondWith(versioned(req));
  else e.respondWith(fromCache(req));
});

function timeout(ms) { return new Promise((_, rej) => setTimeout(() => rej(new Error("timeout")), ms)); }
function stripSearch(req) { const x = new URL(req.url); x.search = ""; return x.href; }
function withRange(req, res) { const range = req.headers.get("range"); return range ? partial(res, range) : res; }

async function networkFirst(req) {
  const cache = await caches.open(CACHE);
  try {
    const res = await Promise.race([fetch(req, { cache: "no-cache" }), timeout(4000)]);
    if (res.ok) cache.put(stripSearch(req), res.clone());
    return res;
  } catch (err) {
    return (await cache.match(stripSearch(req))) || (await cache.match(url("index.html"))) || Response.error();
  }
}

// Sounds with a content hash in the address never change, so a saved copy is always right.
// Not saved yet → download it now (that is the new recording). Offline and not saved → any saved copy.
async function versioned(req) {
  const cache = await caches.open(CACHE);
  const exact = req.url.replace(/[?&](?!v=)[^&]*/g, "");
  let res = await cache.match(exact);
  if (!res) {
    try {
      const r = await fetch(exact);
      if (r.ok && r.status === 200) { await cache.put(exact, r.clone()); res = r; }
    } catch (e) {}
  }
  if (!res) res = await cache.match(stripSearch(req), { ignoreSearch: true });
  return res ? withRange(req, res) : Response.error();
}

// Pictures, fonts (and sounds asked for without a hash): from the device at once, refreshed in the background.
async function fromCache(req) {
  const cache = await caches.open(CACHE);
  const k = stripSearch(req);
  let res = await cache.match(k, { ignoreSearch: true });
  const refresh = fetch(k, { cache: "no-cache" }).then((r) => {
    if (r.ok && r.status === 200) { cache.put(k, r.clone()); return r; }
    r.arrayBuffer().catch(() => {});
    return null;
  }).catch(() => null);
  if (!res) res = await refresh;
  return res ? withRange(req, res) : Response.error();
}

// Safari asks for sounds in pieces (Range requests) and needs a 206 answer.
async function partial(res, range) {
  const buf = await res.clone().arrayBuffer();
  const m = /bytes=(\\d*)-(\\d*)/.exec(range) || [];
  const size = buf.byteLength;
  let start = m[1] ? parseInt(m[1], 10) : 0, end = m[2] ? parseInt(m[2], 10) : size - 1;
  if (!m[1] && m[2]) { start = Math.max(0, size - parseInt(m[2], 10)); end = size - 1; }
  end = Math.min(end, size - 1);
  if (start > end) return new Response(null, { status: 416, headers: { "Content-Range": "bytes */" + size } });
  return new Response(buf.slice(start, end + 1), { status: 206, headers: {
    "Content-Type": res.headers.get("Content-Type") || "application/octet-stream",
    "Content-Range": "bytes " + start + "-" + end + "/" + size,
    "Content-Length": String(end - start + 1), "Accept-Ranges": "bytes" } });
}
`;

const out = path.join(ROOT, "sw.js");
const old = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
if (process.argv.includes("--check")) {
  if (old !== sw) { console.log("sw.js is out of date: run  node tools/build_sw.js"); process.exit(1); }
  console.log(`sw.js up to date (${files.length} files, version ${version})`);
} else {
  fs.writeFileSync(out, sw);
  console.log(`sw.js: ${files.length} files, version ${version}`);
}
